trigger:
- main

strategy:
 matrix:
   linux:
     operatingSystem: 'ubuntu-latest'
   mac:
     operatingSystem: 'macos-latest'
     

pool:
  vmImage: $(operatingSystem)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo Running on $(operatingSystem)
  displayName: 'Run a multi-line script'
